name: Tofu Plan

on:
  pull_request:
    branches:
      - main
    paths:
      - ch5/tofu/lambda/**

jobs:
  plan:
    name: "Tofu Plan"
    runs-on: ubuntu-latest
    
    permissions:
      pull-requests: write
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - uses: aws-actions/configure-aws-credentials@v3
        with:
          
          # TODO: fill in your IAM role ARN!
          role-to-assume: arn:aws:iam::111111111111:role/lambda-deploy-plan
          role-session-name: tofu-plan-${{ github.run_number }}-${{ github.actor }}
          aws-region: us-east-2

      - uses: opentofu/setup-opentofu@v1

      
      - name: tofu plan
        id: tofu_plan
        working-directory: ch5/tofu/lambda
        run: |
          tofu init -no-color -input=false
          tofu plan -no-color -input=false -lock=false

      
      - uses: peter-evans/create-or-update-comment@v4
        if: always()
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## ${{ steps.tofu_plan.outcome == 'success' && '✅' || '⚠️' }} `tofu plan` output
            ```
            ${{ steps.tofu_plan.outputs.stdout }}
            ```